# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  cis:
    image: cis
    build:
      context: .
      dockerfile: cis/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
