# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
name: cis
services:
  app:
    image: cis
    build:
      context: .
      dockerfile: cis/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 3000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
